name: CI-compile

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip gawk

    - name: git checkout
      uses: actions/checkout@v2

    - run: git fetch --prune --unshallow

    - name: Compile -> make all clean release
      run: make --trace all clean release

    - name: Create detailed changelog
      run: sh ./make_changelog.sh

    - name: Upload release artifact ELF
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: DML
        path: |
          doomed-loader-*.elf

    - name: Upload release artifact info
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: INFO
        path: |
          DETAILED_CHANGELOG
          CREDITS
          LICENSE
          README.md

  build-variants:
    strategy:
      fail-fast: false
      matrix:
        rtl: ["", RTL=1]
        pademu: ["", PADEMU=1]
        igs: ["", IGS=1]
        t10k: ["", DTL_T10000=1]
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: apk add build-base git zip gawk

    - name: git checkout
      uses: actions/checkout@v2

    - run: git fetch --prune --unshallow

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make dmlversion)"

    - name: Compile -> make ${{ matrix.t10k }} ${{ matrix.igs }} ${{ matrix.pademu }} ${{ matrix.rtl }} NOT_PACKED=1
      run: |
        make --trace ${{ matrix.t10k }} ${{ matrix.igs }} ${{ matrix.pademu }} ${{ matrix.rtl }} NOT_PACKED=1
        mv doomed-loader.elf DOOMED-LOADER-${{ steps.version.outputs.version }}-${{ matrix.t10k }}-${{ matrix.igs }}-${{ matrix.pademu }}-${{ matrix.rtl }}.ELF

    - name: Create detailed changelog
      run: sh ./make_changelog.sh

    - name: Upload variants artifact ELF
      uses: actions/upload-artifact@v2
      with:
        name: DOOMED-VARIANTS
        path: DOOMED-LOADER*.ELF

  build-debug:
    strategy:
      fail-fast: false
      matrix:
        debug: [debug, iopcore_debug, ingame_debug, deci2_debug] # eesio_debug broken
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: apk add build-base git zip gawk

    - name: git checkout
      uses: actions/checkout@v2

    - run: git fetch --prune --unshallow

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make dmlversion)"

    - name: Compile -> make debug
      run: |
        make ${{ matrix.debug }} --trace
        mv doomed-loader.elf doomed-loader-${{ matrix.debug }}.elf

    - name: Upload variants artifact ELF
      uses: actions/upload-artifact@v2
      with:
        name: opl-debug-${{ steps.version.outputs.version }}-${{ matrix.docker }}
        path: doomed-loader-*.elf

  release:
    needs: [build, build-variants]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
    steps:
    - name: git checkout
      uses: actions/checkout@v2

    - run: git fetch --prune --unshallow

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make dmlversion)"

    - name: Download release artifact
      uses: actions/download-artifact@v1
      with:
        name: DOOMED-LOADER

    - name: Download variants artifact
      uses: actions/download-artifact@v1
      with:
        name: DOOMED-LOADER-VARIANTS

    - name: Download info artifact
      uses: actions/download-artifact@v1
      with:
        name: INFO

    - name: Prepare artifacts for release
      run: |
        cp INFO/* DOOMED/
        cp INFO/* DOOMED-LOADER-VARIANTS/
        7z a -t7z DOOMED-LOADER-${{ steps.version.outputs.version }}.7z DOOMED-LOADER/*
        7z a -t7z DOOMED-LOADER-VARIANTS-${{ steps.version.outputs.version }}.7z DOOMED-LOADER-VARIANTS/*
        cp -f DOOMED-LOADER-${{ steps.version.outputs.version }}.7z DOOMED-LOADER.7z
        cp -f DOOMED-LOADER-VARIANTS-${{ steps.version.outputs.version }}.7z DOOMED-LOADER-VARIANTS.7z

    - name: Create prerelease
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        title: "${{ steps.version.outputs.version }}"
        files: |
          DOOMED-LOADER-${{ steps.version.outputs.version }}.7z
          DOOMED-LOADER-VARIANTS-${{ steps.version.outputs.version }}.7z
          DOOMED-LOADER.7z
          DOOMED-LOADER-VARIANTS.7z

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: "${{ contains(github.ref, '-rc') }}"
        title: "${{ steps.version.outputs.version }}"
        files: |
          DOOMED-LOADER-${{ steps.version.outputs.version }}.7z
          DOOMED-LOADER-VARIANTS-${{ steps.version.outputs.version }}.7z
          DOOMED-LOADER.7z
          DOOMED-LOADER-VARIANTS.7z
          
